FFABS-4 Remove Login/Register throw firebase
apptolast/FFABackSpringGod pull request #2
Opened 2024-10-21 14:21 UTC by Coshiloco

2024-10-25 18:16 UTC, hgarciaalberto requested changes
Fix this!!!

2024-10-25 18:16 UTC, hgarciaalberto commented on src/main/java/com/ffa/back/config/FirebaseAuthenticationWebFilter.java
> +                FirebaseToken decodedToken = FirebaseAuth.getInstance().verifyIdToken(idToken);
No se puede hacer injección de dependencias aqui para no tener que instanciar FirebaseAuth?

2024-10-25 18:16 UTC, hgarciaalberto commented on src/main/java/com/ffa/back/config/SecurityConfig.java
> +}
No puedes formatear mejor este codigo? 
Me daña la vista verlo estos espacios y saltos de linea...

2024-10-25 18:16 UTC, hgarciaalberto commented on src/main/java/com/ffa/back/config/FirebaseAuthenticationWebFilter.java
> +                                .build();
Fix this gañan!

2024-11-27 12:45 UTC, Coshiloco commented on src/main/java/com/ffa/back/config/FirebaseAuthenticationWebFilter.java
> +                FirebaseToken decodedToken = FirebaseAuth.getInstance().verifyIdToken(idToken);
Resuelto

2024-11-27 12:45 UTC, Coshiloco commented on src/main/java/com/ffa/back/config/SecurityConfig.java
> +}
Resuelto

2024-11-27 12:45 UTC, Coshiloco commented on src/main/java/com/ffa/back/config/FirebaseAuthenticationWebFilter.java
> +                                .build();
Resuelto

2024-11-27 13:25 UTC, Coshiloco commented
aprrove

2024-11-27 13:28 UTC, hgarciaalberto approved these changes

2024-11-27 13:29 UTC, merged